FROM node:20-slim
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

ENV NEXT_TELEMETRY_DISABLED=1

ARG BACKEND_URL=http://localhost:9091
ENV BACKEND_URL=${BACKEND_URL}

RUN npm run build

ENV PORT=3000

CMD ["sh", "-c", "node_modules/.bin/next start -p ${PORT}"]
