FROM node:20-slim
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

ENV PORT=3000

CMD ["sh", "-c", "node_modules/.bin/next start -p ${PORT}"]
